[package]
name = "xtask"
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
clap = { version = "4.4.6", default-features = false, features = ["derive", "std", "help"] }
fs-err = "2.9.0"
tempfile = "3.6.0"
